export const UNIFIED_CANDIDATE_DATA = {
  "1": {
    id: "1",
    name: "Lucy Brown",
    email: "lucy.brown@email.com", 
    location: "London, UK",
    phone: "+44 7456 789123",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "new_application", 
    displaySubStatus: "Unopened",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "5 Nov 2024",
    lastPollenTeamMember: "Holly Saunders", 
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "2": {
    id: "2", 
    name: "Emma Thompson",
    email: "emma.thompson@email.com",
    location: "Bristol, UK", 
    phone: "+44 7456 789123",
    profilePicture: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "under_review",
    displaySubStatus: "Unopened", 
    applicationCount: 4,
    hasPollenInteraction: true,
    lastInteractionDate: "10 Nov 2024",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant", 
    company: "TechFlow Solutions"
  },
  "3": {
    id: "3",
    name: "Alex Chen", 
    email: "alex.chen@email.com",
    location: "Manchester, UK",
    phone: "+44 7456 789123", 
    profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "unopened",
    displaySubStatus: "Unopened",
    applicationCount: 2,
    hasPollenInteraction: true, 
    lastInteractionDate: "22 Oct 2024",
    lastPollenTeamMember: "Sophie O'Brien",
    isFastTrack: true,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "4": {
    id: "4",
    name: "Sophie Williams",
    email: "sophie.williams@email.com", 
    location: "Birmingham, UK",
    phone: "+44 7456 123789",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "new_application",
    displaySubStatus: "Unopened",
    applicationCount: 1, 
    hasPollenInteraction: true,
    lastInteractionDate: "1 Dec 2024",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "5": {
    id: "5",
    name: "James Mitchell",
    email: "james.mitchell@email.com",
    location: "Manchester, UK", 
    phone: "+44 7123 456789",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    currentStatus: "in_progress", 
    subStatus: "pollen_interview_complete",
    displaySubStatus: "Pollen Interview Complete",
    applicationCount: 2,
    hasPollenInteraction: true,
    lastInteractionDate: "15 Jan 2025", 
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Social Media Marketing Assistant",
    company: "K7 Media Group" 
  },
  "6": {
    id: "6",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    location: "Edinburgh, UK",
    phone: "+44 7456 123789",
    profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress", 
    subStatus: "invited_to_pollen_interview",
    displaySubStatus: "Invited to Pollen Interview",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null, 
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "7": {
    id: "7",
    name: "David Wilson", 
    email: "david.wilson@email.com",
    location: "Glasgow, UK",
    phone: "+44 7789 012345",
    profilePicture: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "assessment_review", 
    displaySubStatus: "Under Review", 
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "11 Jan 2025",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false, 
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "8": {
    id: "8", 
    name: "Emily Turner",
    email: "emily.turner@email.com",
    location: "Cardiff, UK",
    phone: "+44 7890 123456",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    currentStatus: "matched_to_employer",
    subStatus: "interview_requested", 
    displaySubStatus: "Interview Requested",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "10 Jan 2025", 
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "9": {
    id: "9",
    name: "Tom Harrison",
    email: "tom.harrison@email.com",
    location: "Glasgow, UK",
    phone: "+44 7789 456123",
    profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    currentStatus: "matched_to_employer",
    subStatus: "matched_to_employer",
    displaySubStatus: "Matched",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "12 Jan 2025",
    lastPollenTeamMember: "Sophie O'Brien",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "10": {
    id: "10",
    name: "Rachel Davis",
    email: "rachel.davis@email.com",
    location: "Newcastle, UK",
    phone: "+44 7456 789123",
    profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    currentStatus: "complete",
    subStatus: "hired",
    displaySubStatus: "Hired",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "12 Jan 2025",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "11": {
    id: "11",
    name: "Chris Anderson",
    email: "chris.anderson@email.com",
    location: "Leeds, UK",
    phone: "+44 7123 456789",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "new_application",
    displaySubStatus: "New",
    applicationCount: 0,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "12": {
    id: "12",
    name: "Sophie Miller",
    email: "sophie.miller@email.com",
    location: "Birmingham, UK",
    phone: "+44 7789 012345",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "assessment_submitted",
    displaySubStatus: "In Progress",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "13": {
    id: "13",
    name: "Jake Thompson",
    email: "jake.thompson@email.com",
    location: "Liverpool, UK",
    phone: "+44 7456 123789",
    profilePicture: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "under_review",
    displaySubStatus: "In Progress",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "14": {
    id: "14",
    name: "Lisa Wang",
    email: "lisa.wang@email.com",
    location: "Sheffield, UK",
    phone: "+44 7890 456123",
    profilePicture: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "assessment_review",
    displaySubStatus: "In Progress",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "15": {
    id: "15",
    name: "Ryan O'Connor",
    email: "ryan.oconnor@email.com",
    location: "Brighton, UK",
    phone: "+44 7123 789456",
    profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "unopened",
    displaySubStatus: "New",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "16": {
    id: "16",
    name: "Zoe Clarke",
    email: "zoe.clarke@email.com",
    location: "Oxford, UK",
    phone: "+44 7789 123456",
    profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "invited_to_pollen_interview",
    displaySubStatus: "Invited to Pollen Interview",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "17": {
    id: "17",
    name: "Matt Rodriguez",
    email: "matt.rodriguez@email.com",
    location: "Nottingham, UK",
    phone: "+44 7456 789012",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    currentStatus: "matched_to_employer",
    subStatus: "matched_to_employer",
    displaySubStatus: "Matched",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "10 Jan 2025",
    lastPollenTeamMember: "Karen Whitelaw",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "18": {
    id: "18",
    name: "Hannah Brooks",
    email: "hannah.brooks@email.com",
    location: "Cambridge, UK",
    phone: "+44 7890 123789",
    profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face",
    currentStatus: "complete",
    subStatus: "stopped_at_assessment",
    displaySubStatus: "Not Progressing",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "9 Jan 2025",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "19": {
    id: "19",
    name: "Oliver Smith",
    email: "oliver.smith@email.com",
    location: "York, UK",
    phone: "+44 7123 456012",
    profilePicture: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    currentStatus: "in_progress",
    subStatus: "assessment_submitted",
    displaySubStatus: "In Progress",
    applicationCount: 1,
    hasPollenInteraction: false,
    lastInteractionDate: null,
    lastPollenTeamMember: null,
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "20": {
    id: "20",
    name: "Grace Taylor",
    email: "grace.taylor@email.com",
    location: "Bath, UK",
    phone: "+44 7789 456012",
    profilePicture: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    currentStatus: "complete",
    subStatus: "stopped_at_pollen_interview",
    displaySubStatus: "Not Progressing",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "8 Jan 2025",
    lastPollenTeamMember: "Karen Whitelaw",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  },
  "21": {
    id: "21",
    name: "Daniel Brown",
    email: "daniel.brown@email.com",
    location: "Liverpool, UK",
    phone: "+44 7123 789456",
    profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    currentStatus: "complete",
    subStatus: "stopped_at_employer",
    displaySubStatus: "Not Progressing",
    applicationCount: 1,
    hasPollenInteraction: true,
    lastInteractionDate: "7 Jan 2025",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions",
    employerFeedback: {
      hasUnreviewedFeedback: true,
      overallScore: 85,
      technicalScore: "Excellent",
      problemSolvingScore: "Strong",
      teamFitScore: "Good",
      feedback: "Strategic thinking, excellent questions, genuine company interest.",
      reviewStatus: "pending"
    }
  },
  "28": {
    id: "28",
    name: "Michael Roberts",
    email: "michael.roberts@email.com", 
    location: "Leeds, UK",
    phone: "+44 7456 123789",
    profilePicture: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face",
    currentStatus: "new_applicants",
    subStatus: "new_application",
    displaySubStatus: "Unopened",
    applicationCount: 1, 
    hasPollenInteraction: true,
    lastInteractionDate: "1 Dec 2024",
    lastPollenTeamMember: "Holly Saunders",
    isFastTrack: false,
    jobTitle: "Marketing Assistant",
    company: "TechFlow Solutions"
  }
};

// Helper function to get candidate data consistently across all pages
export const getUnifiedCandidateData = (candidateId) => {
  return UNIFIED_CANDIDATE_DATA[candidateId] || null;
};

// Helper function to format interaction text for display
export const getInteractionDisplayText = (candidateData) => {
  if (candidateData.hasPollenInteraction && candidateData.lastPollenTeamMember && candidateData.lastInteractionDate) {
    return `Spoke to ${candidateData.lastPollenTeamMember} on ${candidateData.lastInteractionDate}`;
  }
  return candidateData.applicationCount === 0 ? "0 previous applications" : `${candidateData.applicationCount} previous application${candidateData.applicationCount === 1 ? '' : 's'}`;
};